#index:
#    path: /
#    controller: App\Controller\DefaultController::index
authentication_token:
    path: /auth/login
    methods: ['POST']
gesdinet_jwt_refresh_token:
    path: /auth/refresh
    controller: gesdinet.jwtrefreshtoken::refresh